spring:
  application:
    name: datos-prod
  datasource:
    url: jdbc:mysql://localhost:3306/product_e_commerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariPoolMySQL
  jpa:
    hibernate:
      ddl-auto: validate   # create | create-drop | validate | update | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
